// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/apresentacao/telas/tecnicos/tecnicos_tela_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:gerenciar/dominio/casos_uso/tecnico/listar_tecnicos.dart'
    as _i3;
import 'package:gerenciar/dominio/entidades/tecnico.dart' as _i5;
import 'package:gerenciar/dominio/interfaces/tecnico_repositorio_interface.dart'
    as _i2;
import 'package:gerenciar/servicos/autenticacao_servico.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTecnicoRepositorioInterface_0 extends _i1.SmartFake
    implements _i2.TecnicoRepositorioInterface {
  _FakeTecnicoRepositorioInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ListarTecnicos].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarTecnicos extends _i1.Mock implements _i3.ListarTecnicos {
  MockListarTecnicos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TecnicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeTecnicoRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.TecnicoRepositorioInterface);

  @override
  _i4.Future<List<_i5.Tecnico>> executar({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i4.Future<List<_i5.Tecnico>>.value(<_i5.Tecnico>[]),
      ) as _i4.Future<List<_i5.Tecnico>>);
}

/// A class which mocks [AutenticacaoServico].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutenticacaoServico extends _i1.Mock
    implements _i6.AutenticacaoServico {
  MockAutenticacaoServico() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> enviarEmailRedefinicaoSenha(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #enviarEmailRedefinicaoSenha,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.User?> login(
    String? email,
    String? senha,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            senha,
          ],
        ),
        returnValue: _i4.Future<_i7.User?>.value(),
      ) as _i4.Future<_i7.User?>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> primeiroGestorJaCadastrado() => (super.noSuchMethod(
        Invocation.method(
          #primeiroGestorJaCadastrado,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i7.User?> cadastrarPrimeiroGestor({
    required String? nome,
    required String? email,
    required String? senha,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cadastrarPrimeiroGestor,
          [],
          {
            #nome: nome,
            #email: email,
            #senha: senha,
          },
        ),
        returnValue: _i4.Future<_i7.User?>.value(),
      ) as _i4.Future<_i7.User?>);

  @override
  _i4.Future<_i7.User?> cadastrarTecnico({
    required String? nome,
    required String? email,
    required String? senha,
    required String? telefone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cadastrarTecnico,
          [],
          {
            #nome: nome,
            #email: email,
            #senha: senha,
            #telefone: telefone,
          },
        ),
        returnValue: _i4.Future<_i7.User?>.value(),
      ) as _i4.Future<_i7.User?>);

  @override
  _i4.Future<Map<String, dynamic>?> buscarDadosUsuarioLogado() =>
      (super.noSuchMethod(
        Invocation.method(
          #buscarDadosUsuarioLogado,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);
}
