# analysis_options.yaml

# Este 'include' importa um conjunto de regras recomendadas pela equipe do Dart.
# Estas regras ajudam a evitar erros comuns e a manter um estilo de código consistente.
include: package:lints/recommended.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
  # Exclui arquivos gerados automaticamente da análise, pois não devemos editá-los.
  exclude:
    - "**/*.mocks.dart" # Exclui os arquivos de mock que geramos para os testes
    - "**/*.g.dart"     # Exclui outros arquivos gerados (caso você use no futuro)

linter:
  # Aqui você pode adicionar ou customizar regras.
  # Por enquanto, vamos manter as recomendadas que já são excelentes.
  rules:
    # Exemplo de regra que você poderia adicionar:
    # prefer_single_quotes: true