// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/servicos/relatorio_servico_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gerenciar/dominio/entidades/cliente.dart' as _i7;
import 'package:gerenciar/dominio/entidades/ordem_servico.dart' as _i4;
import 'package:gerenciar/dominio/entidades/tecnico.dart' as _i9;
import 'package:gerenciar/dominio/interfaces/cliente_repositorio_interface.dart'
    as _i6;
import 'package:gerenciar/dominio/interfaces/ordem_servico_repositorio_interface.dart'
    as _i2;
import 'package:gerenciar/dominio/interfaces/tecnico_repositorio_interface.dart'
    as _i8;
import 'package:gerenciar/servicos/relatorio_servico.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrdemServicoRepositorioInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdemServicoRepositorioInterface extends _i1.Mock
    implements _i2.OrdemServicoRepositorioInterface {
  MockOrdemServicoRepositorioInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.OrdemServico>> listarComFiltros(
    _i5.FiltrosRelatorio? filtros,
    String? idGestor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarComFiltros,
          [
            filtros,
            idGestor,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.OrdemServico>>.value(<_i4.OrdemServico>[]),
      ) as _i3.Future<List<_i4.OrdemServico>>);

  @override
  _i3.Future<void> reabrir({
    required String? id,
    required String? justificativa,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reabrir,
          [],
          {
            #id: id,
            #justificativa: justificativa,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> adicionar(_i4.OrdemServico? ordem) => (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [ordem],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i4.OrdemServico? ordem) => (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [ordem],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.OrdemServico?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i4.OrdemServico?>.value(),
      ) as _i3.Future<_i4.OrdemServico?>);

  @override
  _i3.Future<List<_i4.OrdemServico>> listarTodos({required String? idGestor}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {#idGestor: idGestor},
        ),
        returnValue:
            _i3.Future<List<_i4.OrdemServico>>.value(<_i4.OrdemServico>[]),
      ) as _i3.Future<List<_i4.OrdemServico>>);
}

/// A class which mocks [ClienteRepositorioInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockClienteRepositorioInterface extends _i1.Mock
    implements _i6.ClienteRepositorioInterface {
  MockClienteRepositorioInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> adicionar(_i7.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [cliente],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i7.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [cliente],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i7.Cliente?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i7.Cliente?>.value(),
      ) as _i3.Future<_i7.Cliente?>);

  @override
  _i3.Future<List<_i7.Cliente>> listarTodos({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i3.Future<List<_i7.Cliente>>.value(<_i7.Cliente>[]),
      ) as _i3.Future<List<_i7.Cliente>>);
}

/// A class which mocks [TecnicoRepositorioInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockTecnicoRepositorioInterface extends _i1.Mock
    implements _i8.TecnicoRepositorioInterface {
  MockTecnicoRepositorioInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> adicionar(_i9.Tecnico? tecnico) => (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [tecnico],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i9.Tecnico? tecnico) => (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [tecnico],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.Tecnico?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i9.Tecnico?>.value(),
      ) as _i3.Future<_i9.Tecnico?>);

  @override
  _i3.Future<List<_i9.Tecnico>> listarTodos({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i3.Future<List<_i9.Tecnico>>.value(<_i9.Tecnico>[]),
      ) as _i3.Future<List<_i9.Tecnico>>);
}
