// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/fluxo/cadastro_os_fluxo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:firebase_auth/firebase_auth.dart' as _i21;
import 'package:gerenciar/dominio/casos_uso/cliente/buscar_cliente_por_id.dart'
    as _i9;
import 'package:gerenciar/dominio/casos_uso/cliente/listar_clientes.dart'
    as _i13;
import 'package:gerenciar/dominio/casos_uso/forma_pagamento/listar_formas_pagamento.dart'
    as _i15;
import 'package:gerenciar/dominio/casos_uso/ordem_servico/cadastrar_ordem_servico.dart'
    as _i17;
import 'package:gerenciar/dominio/casos_uso/ordem_servico/listar_ordens_servico.dart'
    as _i6;
import 'package:gerenciar/dominio/casos_uso/tecnico/buscar_tecnico_por_id.dart'
    as _i11;
import 'package:gerenciar/dominio/casos_uso/tecnico/listar_tecnicos.dart'
    as _i14;
import 'package:gerenciar/dominio/entidades/agendamento.dart' as _i19;
import 'package:gerenciar/dominio/entidades/cliente.dart' as _i10;
import 'package:gerenciar/dominio/entidades/forma_pagamento.dart' as _i16;
import 'package:gerenciar/dominio/entidades/ordem_servico.dart' as _i8;
import 'package:gerenciar/dominio/entidades/tecnico.dart' as _i12;
import 'package:gerenciar/dominio/interfaces/agendamento_repositorio_interface.dart'
    as _i18;
import 'package:gerenciar/dominio/interfaces/cliente_repositorio_interface.dart'
    as _i3;
import 'package:gerenciar/dominio/interfaces/forma_pagamento_repositorio_interface.dart'
    as _i5;
import 'package:gerenciar/dominio/interfaces/ordem_servico_repositorio_interface.dart'
    as _i2;
import 'package:gerenciar/dominio/interfaces/tecnico_repositorio_interface.dart'
    as _i4;
import 'package:gerenciar/servicos/autenticacao_servico.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrdemServicoRepositorioInterface_0 extends _i1.SmartFake
    implements _i2.OrdemServicoRepositorioInterface {
  _FakeOrdemServicoRepositorioInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClienteRepositorioInterface_1 extends _i1.SmartFake
    implements _i3.ClienteRepositorioInterface {
  _FakeClienteRepositorioInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTecnicoRepositorioInterface_2 extends _i1.SmartFake
    implements _i4.TecnicoRepositorioInterface {
  _FakeTecnicoRepositorioInterface_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFormaPagamentoRepositorioInterface_3 extends _i1.SmartFake
    implements _i5.FormaPagamentoRepositorioInterface {
  _FakeFormaPagamentoRepositorioInterface_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ListarOrdensServico].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarOrdensServico extends _i1.Mock
    implements _i6.ListarOrdensServico {
  MockListarOrdensServico() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrdemServicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeOrdemServicoRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.OrdemServicoRepositorioInterface);

  @override
  _i7.Future<List<_i8.OrdemServico>> executar({required String? idGestor}) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {#idGestor: idGestor},
        ),
        returnValue:
            _i7.Future<List<_i8.OrdemServico>>.value(<_i8.OrdemServico>[]),
      ) as _i7.Future<List<_i8.OrdemServico>>);
}

/// A class which mocks [BuscarClientePorId].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuscarClientePorId extends _i1.Mock
    implements _i9.BuscarClientePorId {
  MockBuscarClientePorId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ClienteRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeClienteRepositorioInterface_1(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i3.ClienteRepositorioInterface);

  @override
  _i7.Future<_i10.Cliente?> executar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #executar,
          [id],
        ),
        returnValue: _i7.Future<_i10.Cliente?>.value(),
      ) as _i7.Future<_i10.Cliente?>);
}

/// A class which mocks [BuscarTecnicoPorId].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuscarTecnicoPorId extends _i1.Mock
    implements _i11.BuscarTecnicoPorId {
  MockBuscarTecnicoPorId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TecnicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeTecnicoRepositorioInterface_2(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i4.TecnicoRepositorioInterface);

  @override
  _i7.Future<_i12.Tecnico?> executar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #executar,
          [id],
        ),
        returnValue: _i7.Future<_i12.Tecnico?>.value(),
      ) as _i7.Future<_i12.Tecnico?>);
}

/// A class which mocks [ListarClientes].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarClientes extends _i1.Mock implements _i13.ListarClientes {
  MockListarClientes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ClienteRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeClienteRepositorioInterface_1(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i3.ClienteRepositorioInterface);

  @override
  _i7.Future<List<_i10.Cliente>> executar({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i7.Future<List<_i10.Cliente>>.value(<_i10.Cliente>[]),
      ) as _i7.Future<List<_i10.Cliente>>);
}

/// A class which mocks [ListarTecnicos].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarTecnicos extends _i1.Mock implements _i14.ListarTecnicos {
  MockListarTecnicos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TecnicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeTecnicoRepositorioInterface_2(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i4.TecnicoRepositorioInterface);

  @override
  _i7.Future<List<_i12.Tecnico>> executar({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i7.Future<List<_i12.Tecnico>>.value(<_i12.Tecnico>[]),
      ) as _i7.Future<List<_i12.Tecnico>>);
}

/// A class which mocks [ListarFormasPagamento].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarFormasPagamento extends _i1.Mock
    implements _i15.ListarFormasPagamento {
  MockListarFormasPagamento() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FormaPagamentoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeFormaPagamentoRepositorioInterface_3(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i5.FormaPagamentoRepositorioInterface);

  @override
  _i7.Future<List<_i16.FormaPagamento>> executar({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i7.Future<List<_i16.FormaPagamento>>.value(
            <_i16.FormaPagamento>[]),
      ) as _i7.Future<List<_i16.FormaPagamento>>);
}

/// A class which mocks [CadastrarOrdemServico].
///
/// See the documentation for Mockito's code generation for more information.
class MockCadastrarOrdemServico extends _i1.Mock
    implements _i17.CadastrarOrdemServico {
  MockCadastrarOrdemServico() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrdemServicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeOrdemServicoRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.OrdemServicoRepositorioInterface);

  @override
  _i7.Future<void> executar(_i8.OrdemServico? ordem) => (super.noSuchMethod(
        Invocation.method(
          #executar,
          [ordem],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [AgendamentoRepositorioInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendamentoRepositorioInterface extends _i1.Mock
    implements _i18.AgendamentoRepositorioInterface {
  MockAgendamentoRepositorioInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> verificarDisponibilidade(
    String? idTecnico,
    DateTime? dataHora,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verificarDisponibilidade,
          [
            idTecnico,
            dataHora,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> adicionar(_i19.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [agendamento],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> atualizar(_i19.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [agendamento],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> reativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reativar,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i19.Agendamento?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i7.Future<_i19.Agendamento?>.value(),
      ) as _i7.Future<_i19.Agendamento?>);

  @override
  _i7.Future<List<_i19.Agendamento>> listarTodos({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue:
            _i7.Future<List<_i19.Agendamento>>.value(<_i19.Agendamento>[]),
      ) as _i7.Future<List<_i19.Agendamento>>);
}

/// A class which mocks [AutenticacaoServico].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutenticacaoServico extends _i1.Mock
    implements _i20.AutenticacaoServico {
  MockAutenticacaoServico() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> enviarEmailRedefinicaoSenha(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #enviarEmailRedefinicaoSenha,
          [email],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i21.User?> login(
    String? email,
    String? senha,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            senha,
          ],
        ),
        returnValue: _i7.Future<_i21.User?>.value(),
      ) as _i7.Future<_i21.User?>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> primeiroGestorJaCadastrado() => (super.noSuchMethod(
        Invocation.method(
          #primeiroGestorJaCadastrado,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i21.User?> cadastrarPrimeiroGestor({
    required String? nome,
    required String? email,
    required String? senha,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cadastrarPrimeiroGestor,
          [],
          {
            #nome: nome,
            #email: email,
            #senha: senha,
          },
        ),
        returnValue: _i7.Future<_i21.User?>.value(),
      ) as _i7.Future<_i21.User?>);

  @override
  _i7.Future<_i21.User?> cadastrarTecnico({
    required String? nome,
    required String? email,
    required String? senha,
    required String? telefone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cadastrarTecnico,
          [],
          {
            #nome: nome,
            #email: email,
            #senha: senha,
            #telefone: telefone,
          },
        ),
        returnValue: _i7.Future<_i21.User?>.value(),
      ) as _i7.Future<_i21.User?>);

  @override
  _i7.Future<void> salvarTokenDoDispositivo() => (super.noSuchMethod(
        Invocation.method(
          #salvarTokenDoDispositivo,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> buscarDadosUsuarioLogado() =>
      (super.noSuchMethod(
        Invocation.method(
          #buscarDadosUsuarioLogado,
          [],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);
}
