// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/fluxo/cadastro_cliente_fluxo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i12;

import 'package:firebase_auth/firebase_auth.dart' as _i9;
import 'package:gerenciar/dominio/casos_uso/cliente/cadastrar_cliente.dart'
    as _i7;
import 'package:gerenciar/dominio/casos_uso/cliente/listar_clientes.dart'
    as _i4;
import 'package:gerenciar/dominio/entidades/cliente.dart' as _i6;
import 'package:gerenciar/dominio/interfaces/cliente_repositorio_interface.dart'
    as _i2;
import 'package:gerenciar/servicos/autenticacao_servico.dart' as _i8;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClienteRepositorioInterface_0 extends _i1.SmartFake
    implements _i2.ClienteRepositorioInterface {
  _FakeClienteRepositorioInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_2 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ListarClientes].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarClientes extends _i1.Mock implements _i4.ListarClientes {
  MockListarClientes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClienteRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeClienteRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.ClienteRepositorioInterface);

  @override
  _i5.Future<List<_i6.Cliente>> executar({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i5.Future<List<_i6.Cliente>>.value(<_i6.Cliente>[]),
      ) as _i5.Future<List<_i6.Cliente>>);
}

/// A class which mocks [CadastrarCliente].
///
/// See the documentation for Mockito's code generation for more information.
class MockCadastrarCliente extends _i1.Mock implements _i7.CadastrarCliente {
  MockCadastrarCliente() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClienteRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeClienteRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.ClienteRepositorioInterface);

  @override
  _i5.Future<void> executar(_i6.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #executar,
          [cliente],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AutenticacaoServico].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutenticacaoServico extends _i1.Mock
    implements _i8.AutenticacaoServico {
  MockAutenticacaoServico() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> enviarEmailRedefinicaoSenha(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #enviarEmailRedefinicaoSenha,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i9.User?> login(
    String? email,
    String? senha,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            senha,
          ],
        ),
        returnValue: _i5.Future<_i9.User?>.value(),
      ) as _i5.Future<_i9.User?>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> primeiroGestorJaCadastrado() => (super.noSuchMethod(
        Invocation.method(
          #primeiroGestorJaCadastrado,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i9.User?> cadastrarPrimeiroGestor({
    required String? nome,
    required String? email,
    required String? senha,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cadastrarPrimeiroGestor,
          [],
          {
            #nome: nome,
            #email: email,
            #senha: senha,
          },
        ),
        returnValue: _i5.Future<_i9.User?>.value(),
      ) as _i5.Future<_i9.User?>);

  @override
  _i5.Future<_i9.User?> cadastrarTecnico({
    required String? nome,
    required String? email,
    required String? senha,
    required String? telefone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cadastrarTecnico,
          [],
          {
            #nome: nome,
            #email: email,
            #senha: senha,
            #telefone: telefone,
          },
        ),
        returnValue: _i5.Future<_i9.User?>.value(),
      ) as _i5.Future<_i9.User?>);

  @override
  _i5.Future<Map<String, dynamic>?> buscarDadosUsuarioLogado({bool forcarAtualizacao = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #buscarDadosUsuarioLogado,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response>);

  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i12.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
      ) as _i5.Future<_i12.Uint8List>);

  @override
  _i5.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_2(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
