// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/apresentacao/telas/ordens_servico/detalhes_os_tela_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:gerenciar/dominio/casos_uso/cliente/buscar_cliente_por_id.dart'
    as _i4;
import 'package:gerenciar/dominio/casos_uso/tecnico/buscar_tecnico_por_id.dart'
    as _i7;
import 'package:gerenciar/dominio/entidades/cliente.dart' as _i6;
import 'package:gerenciar/dominio/entidades/tecnico.dart' as _i8;
import 'package:gerenciar/dominio/interfaces/cliente_repositorio_interface.dart'
    as _i2;
import 'package:gerenciar/dominio/interfaces/tecnico_repositorio_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClienteRepositorioInterface_0 extends _i1.SmartFake
    implements _i2.ClienteRepositorioInterface {
  _FakeClienteRepositorioInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTecnicoRepositorioInterface_1 extends _i1.SmartFake
    implements _i3.TecnicoRepositorioInterface {
  _FakeTecnicoRepositorioInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BuscarClientePorId].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuscarClientePorId extends _i1.Mock
    implements _i4.BuscarClientePorId {
  MockBuscarClientePorId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClienteRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeClienteRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.ClienteRepositorioInterface);

  @override
  _i5.Future<_i6.Cliente?> executar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #executar,
          [id],
        ),
        returnValue: _i5.Future<_i6.Cliente?>.value(),
      ) as _i5.Future<_i6.Cliente?>);
}

/// A class which mocks [BuscarTecnicoPorId].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuscarTecnicoPorId extends _i1.Mock
    implements _i7.BuscarTecnicoPorId {
  MockBuscarTecnicoPorId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TecnicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeTecnicoRepositorioInterface_1(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i3.TecnicoRepositorioInterface);

  @override
  _i5.Future<_i8.Tecnico?> executar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #executar,
          [id],
        ),
        returnValue: _i5.Future<_i8.Tecnico?>.value(),
      ) as _i5.Future<_i8.Tecnico?>);
}
