// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/apresentacao/telas/ordens_servico/editar_os_tela_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gerenciar/dominio/casos_uso/ordem_servico/atualizar_ordem_servico.dart'
    as _i3;
import 'package:gerenciar/dominio/entidades/ordem_servico.dart' as _i5;
import 'package:gerenciar/dominio/interfaces/ordem_servico_repositorio_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOrdemServicoRepositorioInterface_0 extends _i1.SmartFake
    implements _i2.OrdemServicoRepositorioInterface {
  _FakeOrdemServicoRepositorioInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AtualizarOrdemServico].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtualizarOrdemServico extends _i1.Mock
    implements _i3.AtualizarOrdemServico {
  MockAtualizarOrdemServico() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrdemServicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeOrdemServicoRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.OrdemServicoRepositorioInterface);

  @override
  _i4.Future<void> executar(_i5.OrdemServico? ordem) => (super.noSuchMethod(
        Invocation.method(
          #executar,
          [ordem],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
