// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/apresentacao/telas/relatorios/relatorios_tela_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:gerenciar/dominio/casos_uso/cliente/listar_clientes.dart'
    as _i9;
import 'package:gerenciar/dominio/casos_uso/tecnico/listar_tecnicos.dart'
    as _i7;
import 'package:gerenciar/dominio/entidades/cliente.dart' as _i10;
import 'package:gerenciar/dominio/entidades/ordem_servico_detalhada.dart'
    as _i6;
import 'package:gerenciar/dominio/entidades/tecnico.dart' as _i8;
import 'package:gerenciar/dominio/interfaces/cliente_repositorio_interface.dart'
    as _i3;
import 'package:gerenciar/dominio/interfaces/tecnico_repositorio_interface.dart'
    as _i2;
import 'package:gerenciar/servicos/relatorio_servico.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTecnicoRepositorioInterface_0 extends _i1.SmartFake
    implements _i2.TecnicoRepositorioInterface {
  _FakeTecnicoRepositorioInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClienteRepositorioInterface_1 extends _i1.SmartFake
    implements _i3.ClienteRepositorioInterface {
  _FakeClienteRepositorioInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RelatorioServico].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelatorioServico extends _i1.Mock implements _i4.RelatorioServico {
  MockRelatorioServico() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.OrdemServicoDetalhada>> gerarRelatorioOrdensServico(
          _i4.FiltrosRelatorio? filtros) =>
      (super.noSuchMethod(
        Invocation.method(
          #gerarRelatorioOrdensServico,
          [filtros],
        ),
        returnValue: _i5.Future<List<_i6.OrdemServicoDetalhada>>.value(
            <_i6.OrdemServicoDetalhada>[]),
      ) as _i5.Future<List<_i6.OrdemServicoDetalhada>>);
}

/// A class which mocks [ListarTecnicos].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarTecnicos extends _i1.Mock implements _i7.ListarTecnicos {
  MockListarTecnicos() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TecnicoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeTecnicoRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.TecnicoRepositorioInterface);

  @override
  _i5.Future<List<_i8.Tecnico>> executar({bool? incluirInativos = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {#incluirInativos: incluirInativos},
        ),
        returnValue: _i5.Future<List<_i8.Tecnico>>.value(<_i8.Tecnico>[]),
      ) as _i5.Future<List<_i8.Tecnico>>);
}

/// A class which mocks [ListarClientes].
///
/// See the documentation for Mockito's code generation for more information.
class MockListarClientes extends _i1.Mock implements _i9.ListarClientes {
  MockListarClientes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ClienteRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeClienteRepositorioInterface_1(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i3.ClienteRepositorioInterface);

  @override
  _i5.Future<List<_i10.Cliente>> executar({bool? incluirInativos = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [],
          {#incluirInativos: incluirInativos},
        ),
        returnValue: _i5.Future<List<_i10.Cliente>>.value(<_i10.Cliente>[]),
      ) as _i5.Future<List<_i10.Cliente>>);
}
