// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/apresentacao/telas/clientes/editar_cliente_tela_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gerenciar/dominio/entidades/cliente.dart' as _i4;
import 'package:gerenciar/dominio/interfaces/cliente_repositorio_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ClienteRepositorioInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockClienteRepositorioInterface extends _i1.Mock
    implements _i2.ClienteRepositorioInterface {
  MockClienteRepositorioInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> adicionar(_i4.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [cliente],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i4.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [cliente],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Cliente?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i4.Cliente?>.value(),
      ) as _i3.Future<_i4.Cliente?>);

  @override
  _i3.Future<List<_i4.Cliente>> listarTodos({
    required String? idGestor,
    bool? incluirInativos = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {
            #idGestor: idGestor,
            #incluirInativos: incluirInativos,
          },
        ),
        returnValue: _i3.Future<List<_i4.Cliente>>.value(<_i4.Cliente>[]),
      ) as _i3.Future<List<_i4.Cliente>>);
}
