// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/dominio/casos_uso/agendamento/cadastrar_agendamento_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gerenciar/dominio/entidades/agendamento.dart' as _i4;
import 'package:gerenciar/dominio/interfaces/agendamento_repositorio_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AgendamentoRepositorioInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendamentoRepositorioInterface extends _i1.Mock
    implements _i2.AgendamentoRepositorioInterface {
  MockAgendamentoRepositorioInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> verificarDisponibilidade(
    String? idTecnico,
    DateTime? dataHora,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verificarDisponibilidade,
          [
            idTecnico,
            dataHora,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> adicionar(_i4.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [agendamento],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i4.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [agendamento],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Agendamento?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i4.Agendamento?>.value(),
      ) as _i3.Future<_i4.Agendamento?>);

  @override
  _i3.Future<List<_i4.Agendamento>> listarTodos() => (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Agendamento>>.value(<_i4.Agendamento>[]),
      ) as _i3.Future<List<_i4.Agendamento>>);
}
