// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/apresentacao/telas/agendamentos/agendamentos_tela_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gerenciar/dados/repositorios/agendamento/agendamento_repositorio_adaptativo.dart'
    as _i2;
import 'package:gerenciar/dados/repositorios/cliente/cliente_repositorio_adaptativo.dart'
    as _i5;
import 'package:gerenciar/dados/repositorios/tecnico/tecnico_repositorio_adaptativo.dart'
    as _i7;
import 'package:gerenciar/dominio/entidades/agendamento.dart' as _i4;
import 'package:gerenciar/dominio/entidades/cliente.dart' as _i6;
import 'package:gerenciar/dominio/entidades/tecnico.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AgendamentoRepositorioAdaptativo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendamentoRepositorioAdaptativo extends _i1.Mock
    implements _i2.AgendamentoRepositorioAdaptativo {
  MockAgendamentoRepositorioAdaptativo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> verificarDisponibilidade(
    String? idTecnico,
    DateTime? dataHora,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verificarDisponibilidade,
          [
            idTecnico,
            dataHora,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> adicionar(_i4.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [agendamento],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i4.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [agendamento],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Agendamento?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i4.Agendamento?>.value(),
      ) as _i3.Future<_i4.Agendamento?>);

  @override
  _i3.Future<List<_i4.Agendamento>> listarTodos(
          {bool? incluirInativos = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {#incluirInativos: incluirInativos},
        ),
        returnValue:
            _i3.Future<List<_i4.Agendamento>>.value(<_i4.Agendamento>[]),
      ) as _i3.Future<List<_i4.Agendamento>>);
}

/// A class which mocks [ClienteRepositorioAdaptativo].
///
/// See the documentation for Mockito's code generation for more information.
class MockClienteRepositorioAdaptativo extends _i1.Mock
    implements _i5.ClienteRepositorioAdaptativo {
  MockClienteRepositorioAdaptativo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> adicionar(_i6.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [cliente],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i6.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [cliente],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.Cliente?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i6.Cliente?>.value(),
      ) as _i3.Future<_i6.Cliente?>);

  @override
  _i3.Future<List<_i6.Cliente>> listarTodos({bool? incluirInativos = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {#incluirInativos: incluirInativos},
        ),
        returnValue: _i3.Future<List<_i6.Cliente>>.value(<_i6.Cliente>[]),
      ) as _i3.Future<List<_i6.Cliente>>);
}

/// A class which mocks [TecnicoRepositorioAdaptativo].
///
/// See the documentation for Mockito's code generation for more information.
class MockTecnicoRepositorioAdaptativo extends _i1.Mock
    implements _i7.TecnicoRepositorioAdaptativo {
  MockTecnicoRepositorioAdaptativo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> adicionar(_i8.Tecnico? tecnico) => (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [tecnico],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> atualizar(_i8.Tecnico? tecnico) => (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [tecnico],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> inativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #inativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reativar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #reativar,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i8.Tecnico?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i3.Future<_i8.Tecnico?>.value(),
      ) as _i3.Future<_i8.Tecnico?>);

  @override
  _i3.Future<List<_i8.Tecnico>> listarTodos({bool? incluirInativos = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {#incluirInativos: incluirInativos},
        ),
        returnValue: _i3.Future<List<_i8.Tecnico>>.value(<_i8.Tecnico>[]),
      ) as _i3.Future<List<_i8.Tecnico>>);
}
