// Mocks generated by Mockito 5.4.6 from annotations
// in gerenciar/test/apresentacao/telas/agendamentos/editar_agendamento_tela_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gerenciar/dados/repositorios/agendamento/agendamento_repositorio_adaptativo.dart'
    as _i6;
import 'package:gerenciar/dominio/casos_uso/agendamento/atualizar_agendamento.dart'
    as _i3;
import 'package:gerenciar/dominio/entidades/agendamento.dart' as _i5;
import 'package:gerenciar/dominio/interfaces/agendamento_repositorio_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAgendamentoRepositorioInterface_0 extends _i1.SmartFake
    implements _i2.AgendamentoRepositorioInterface {
  _FakeAgendamentoRepositorioInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AtualizarAgendamento].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtualizarAgendamento extends _i1.Mock
    implements _i3.AtualizarAgendamento {
  MockAtualizarAgendamento() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AgendamentoRepositorioInterface get repositorio => (super.noSuchMethod(
        Invocation.getter(#repositorio),
        returnValue: _FakeAgendamentoRepositorioInterface_0(
          this,
          Invocation.getter(#repositorio),
        ),
      ) as _i2.AgendamentoRepositorioInterface);

  @override
  _i4.Future<void> executar(_i5.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #executar,
          [agendamento],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AgendamentoRepositorioAdaptativo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendamentoRepositorioAdaptativo extends _i1.Mock
    implements _i6.AgendamentoRepositorioAdaptativo {
  MockAgendamentoRepositorioAdaptativo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> verificarDisponibilidade(
    String? idTecnico,
    DateTime? dataHora, {
    String? idExcluir,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verificarDisponibilidade,
          [
            idTecnico,
            dataHora,
          ],
          {#idExcluir: idExcluir},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> adicionar(_i5.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #adicionar,
          [agendamento],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> atualizar(_i5.Agendamento? agendamento) =>
      (super.noSuchMethod(
        Invocation.method(
          #atualizar,
          [agendamento],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Agendamento?> buscarPorId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #buscarPorId,
          [id],
        ),
        returnValue: _i4.Future<_i5.Agendamento?>.value(),
      ) as _i4.Future<_i5.Agendamento?>);

  @override
  _i4.Future<List<_i5.Agendamento>> listarTodos({required String? idGestor}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarTodos,
          [],
          {#idGestor: idGestor},
        ),
        returnValue:
            _i4.Future<List<_i5.Agendamento>>.value(<_i5.Agendamento>[]),
      ) as _i4.Future<List<_i5.Agendamento>>);
}
